### ISSUE TITLE
Pls make this

### ISSUE THREAD

**Issue by Ruomi123** [vorlie/YoutubeDL#1]
when click download button it create a popup window and show video info, Progressbar, time download

**Comment by vorlie** [comment]
To be honest, i tried making the progress bar and it wasn't so good. It was a pain to work with.

```py
def show_progress(stream, chunk, bytes_remaining):
    total_size = stream.filesize
    bytes_downloaded = total_size - bytes_remaining
    progress = (bytes_downloaded / total_size) * 100
    sg.one_line_progress_meter('Downloading', progress, 100, '-Downloading-')
```

About the video info, I can do that. And I don't know what do you mean by "time download" like when it was downloaded?

**Comment by Ruomi123** [comment]
> To be honest, i tried making the progress bar and it wasn't so good. It was a pain to work with.
> 
> ```python
> def show_progress(stream, chunk, bytes_remaining):
>     total_size = stream.filesize
>     bytes_downloaded = total_size - bytes_remaining
>     progress = (bytes_downloaded / total_size) * 100
>     sg.one_line_progress_meter('Downloading', progress, 100, '-Downloading-')
> ```
> 
> About the video info, I can do that. And I don't know what do you mean by "time download" like when it was downloaded?


I mean Show How long has it been downloading

**Comment by vorlie** [comment]
What do you think?

![Zrzut ekranu 2023-10-26 o 10 02 15](https://github.com/vorlie/YoutubeDL/assets/99135647/a655e19b-049c-4842-90b4-18b5f82b5d93)

**Comment by Ruomi123** [comment]
> What do you think?
> 
> ![Zrzut ekranu 2023-10-26 o 10 02 15](https://user-images.githubusercontent.com/99135647/278256512-a655e19b-049c-4842-90b4-18b5f82b5d93.png)

Maybe with a popup window would be nice

**Comment by vorlie** [comment]
I dont see a point of another window.

**Comment by vorlie** [comment]
Closing this because I released it.
